const $ = id => document.getElementById(id);
let book = null, index = 0, working = false;
async function api(method,data) {const r=await window.nori.call(method,data);if(!r.ok)throw Error(r.error);return r.data;}
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
async function task(fn, message='İşlem sürüyor…') {
  if(working)return;
  working=true; status(message);
  const controls=[...document.querySelectorAll('button,input,select,textarea')];
  controls.forEach(el=>el.disabled=true);
  try {await fn();} catch(e){status(e.message,true);} finally {working=false;controls.forEach(el=>el.disabled=false);}
}
function tab(name){document.querySelectorAll('.tab').forEach(el=>el.hidden=el.id!==`tab-${name}`);document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===name));}
document.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>task(async()=>{tab(el.dataset.tab);if(el.dataset.tab==='library')await library();status('Hazır.');})));
async function library(){const books=await api('list');$('books').replaceChildren();if(!books.length){$('books').textContent='Henüz kitap yok. İlk masalınızı oluşturun.';return;}for(const b of books){const card=document.createElement('article'),title=document.createElement('h2'),meta=document.createElement('p'),btn=document.createElement('button');title.textContent=b.title;meta.textContent=`${b.pages} sayfa · ${new Date(b.created).toLocaleDateString('tr-TR')}`;btn.textContent='Kitabı aç';btn.addEventListener('click',()=>task(async()=>{book=await api('load',b.id);index=0;render();tab('reader');status('Kitap açıldı.');}));card.append(title,meta,btn);$('books').append(card);}}
function metrics(r){$('report').replaceChildren();for(const [name,value,ok] of [['Sayfa',r.pages,r.pagePass],['Toplam kelime',r.words,r.wordPass],['Hazır resim',`${r.images}/${r.pages}`,r.images===r.pages],['Güncel ses',`${r.audio}/${r.pages}`,r.audio===r.pages]]){const row=document.createElement('div'),label=document.createElement('span'),v=document.createElement('strong');row.className='metric';label.textContent=name;v.textContent=`${ok?'✓':'○'} ${value}`;v.className=ok?'good':'bad';row.append(label,v);$('report').append(row);}}
function render(){if(!book)return;$('empty').hidden=true;$('book-view').hidden=false;$('book-title').textContent=book.title;const p=book.pages[index];$('illustration').replaceChildren();if(p.imageURL){const img=document.createElement('img');img.src=p.imageURL;img.alt=`${book.title}, sayfa ${index+1}`;$('illustration').append(img);}else $('illustration').textContent='✧ Bu sayfanın resmini üretin';$('page-text').textContent=p.text;$('page-number').textContent=`${index+1} / ${book.pages.length}`;$('audio').pause();$('audio').removeAttribute('src');$('audio').hidden=!p.audioURL;if(p.audioURL)$('audio').src=p.audioURL;$('audio').load();$('edit-text').value=p.text;$('edit-prompt').value=p.imagePrompt;metrics(book.report);for(const name of ['theme','age','likeness','voice','complete'])$('review').elements[name].checked=!!book.review?.[name];$('review').elements.notes.value=book.review?.notes||'';}
function unsaved(){return book&&($('edit-text').value!==book.pages[index].text||$('edit-prompt').value!==book.pages[index].imagePrompt);}
function navigate(delta){if(working)return;if(unsaved()&&!confirm('Kaydedilmemiş sayfa değişiklikleri var. Vazgeçilsin mi?'))return;index=Math.max(0,Math.min(book.pages.length-1,index+delta));render();}
$('prev').onclick=()=>navigate(-1);$('next').onclick=()=>navigate(1);
$('audio').addEventListener('ended',()=>{if($('autoplay').checked&&index<book.pages.length-1&&!working&&!unsaved()){navigate(1);if(book.pages[index].audioURL)$('audio').play().catch(()=>status('Dinlemek için oynat düğmesine basın.'));}});
for(const kind of ['photos','voice'])$(`pick-${kind}`).onclick=()=>task(async()=>{const names=await api('pick',kind);if(names)$(kind).textContent=names.map((n,i)=>`${i+1}. ${n}`).join(' · ');status('Seçim yerelde hazır; henüz API’ye gönderilmedi.');});
$('settings-form').onsubmit=e=>{e.preventDefault();const input={key:$('api-key').value,remember:$('remember').checked,textModel:$('text-model').value,imageModel:$('image-model').value,audioModel:$('audio-model').value};task(async()=>{await api('save-settings',input);$('api-key').value='';const s=await api('settings');$('key-status').textContent=s.hasKey?'API anahtarı hazır':'API ayarlanmamış';status('Ayarlar kaydedildi.');});};
$('models').onclick=()=>task(async()=>{const models=await api('models');for(const type of ['text','image','audio']){const list=$(`${type}-models`);list.replaceChildren();models.filter(m=>type==='audio'?m.output.includes('speech'):m.output.includes(type)).forEach(m=>{const o=document.createElement('option');o.value=m.id;o.label=m.name;list.append(o);});}$('model-info').textContent=`${models.length} model bulundu. Alanlara yazmaya başlayarak seçebilirsiniz. Fiyatlar/model desteği OpenRouter hesabınızdan kontrol edilmelidir; otomatik model seçilmez.`;status('Canlı model listesi güncellendi.');});
$('brief').onsubmit=e=>{e.preventDefault();const input=Object.fromEntries(new FormData(e.target));input.consent=e.target.elements.consent.checked;task(async()=>{book=await api('create',input);index=0;render();tab('reader');status('Masal metni kaydedildi. Önce okuyun; sonra bir sayfanın resim ve sesini deneyin.');},'Masal metni yazılıyor. Sayfa ve kelime sınırları kontrol edilecek…');};
async function generate(kind,all){if(unsaved()){status('Önce sayfa değişikliklerini kaydedin.',true);return;}const count=all?book.pages.filter(p=>!p[kind]).length:1;if(!count){status('Eksik sayfa yok.');return;}if(!confirm(`${count} sayfa için ${kind==='image'?'fotoğraflar':'ses örneği'} sağlayıcıya gönderilecek ve ücretli üretim yapılacak. Başlatılsın mı?`))return;await task(async()=>{try{book=await api('generate',{id:book.id,index,kind,all});}catch(e){book=await api('load',book.id);render();throw e;}render();status('Üretim tamamlandı ve kaydedildi. Sonucu kontrol edin.');},'Üretim başladı. Uygulamayı kapatmayın…');}
$('image-one').onclick=()=>generate('image',false);$('audio-one').onclick=()=>generate('audio',false);$('image-all').onclick=()=>generate('image',true);$('audio-all').onclick=()=>generate('audio',true);
$('save-page').onclick=()=>{const input={id:book.id,index,text:$('edit-text').value,imagePrompt:$('edit-prompt').value};task(async()=>{book=await api('edit',input);render();status('Sayfa kaydedildi; değişen içeriğin resim/sesini yeniden üretin.');});};
$('review').onsubmit=e=>{e.preventDefault();const input={id:book.id,notes:e.target.elements.notes.value};for(const name of ['theme','age','likeness','voice','complete'])input[name]=e.target.elements[name].checked;task(async()=>{await api('review',input);book=await api('load',book.id);render();status('Test değerlendirmeniz kaydedildi.');});};
$('export').onclick=()=>task(async()=>{if(unsaved())throw Error('Önce sayfa değişikliklerini kaydedin.');const file=await api('export',book.id);status(file?`Çevrimdışı kitap kaydedildi: ${file}\nPDF için dosyayı tarayıcıda açıp Yazdır → PDF olarak kaydet seçin. Sesler kitap klasöründe MP3 olarak da bulunur.`:'Dışa aktarım iptal edildi.');});
$('open-root').onclick=()=>task(async()=>{await api('folder');status('Kayıt klasörü açıldı.');});$('book-folder').onclick=()=>task(async()=>{await api('folder',book.id);status('Kitap klasörü açıldı.');});$('refresh').onclick=()=>task(async()=>{await library();status('Kitaplık güncellendi.');});
window.nori.progress(message=>status(message));
task(async()=>{const s=await api('settings');$('text-model').value=s.textModel;$('image-model').value=s.imageModel;$('audio-model').value=s.audioModel;$('storage').textContent=s.storage;$('key-status').textContent=s.hasKey?'API anahtarı hazır':'API ayarlanmamış';status(s.hasKey?'Hazır. Yeni bir masal oluşturabilirsiniz.':'Başlamak için API & modeller bölümüne anahtarınızı girip modelleri seçin.');});
